IdentityApp/Controllers/RolesController.cs
using IdentityApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace IdentityApp.Controllers
{
    [Authorize]//HomeController deki herhangi bir Action a gidebilmek icin Cookie ihtiyac duyulacaktir.
    public class RolesController : Controller
    {//https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.rolemanager-1?view=aspnetcore-7.0
        
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RolesController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AppRole model)
        {
            if (ModelState.IsValid)
            {
                var result=await _roleManager.CreateAsync(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("",err.Description);
                }
            }
            return View(model);
        }
    
        [HttpGet]
        public async Task<IActionResult> Edit(string  id)
        {
            var role=await _roleManager.FindByIdAsync(id);
            if (role!=null && role.Name!=null)
            {
                ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);
                return View(role);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AppRole model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);

                if (role!=null)
                {
                    role.Name = model.Name;
                    var result=await _roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    foreach (var err in result.Errors)
                    {
                        ModelState.AddModelError("",err.Description);
                    }
                    if(role.Name!=null)
                        ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

IdentityApp/Controllers/UserController.cs
using IdentityApp.Models;
using IdentityApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IdentityApp.Controllers
{
    public class UserController : Controller
    {
        private UserManager<AppUser> _userManager;
        private RoleManager<AppRole> _roleManager;

        public UserController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users);
        }
        public IActionResult Create()
        {//create formunu gostermek icin
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser{
                    UserName= model.Email,
                    Email=model.Email,
                    FullName=model.FullName
                };
                IdentityResult result =await _userManager.CreateAsync(user,model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("",error.Description);
                    }
                }
                
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
          
            if (id==null)
            {
                return RedirectToAction("Index");

            }
            var user =await _userManager.FindByIdAsync(id);
            if (user!=null)
            {
                //rollero controller den view e tasiyacagiz
                ViewBag.Roles = await _roleManager.Roles.Select(i=>i.Name).ToListAsync();
                return View(new EditUserViewModel
                {
                    Id = user.Id,
                    FullName=user.FullName,
                    Email=user.Email,
                    SelectedRoles=await _userManager.GetRolesAsync(user),
                });

            }//eger böyle bir kullanici yoksa tekrar indexe yönlendirilir.
            return RedirectToAction("Index");

        }

        [HttpPost]
     public async Task< IActionResult> Edit(EditUserViewModel model,string id)
        {//route den gelen id ile url den gelen id karsilastiracagiz
            if (id!=model.Id)
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                var user=await _userManager.FindByIdAsync (model.Id);
                if (user!=null)
                {
                    user.Email = model.Email;
                    user.FullName = model.FullName;
                    var result=await _userManager.UpdateAsync(user);
                    if (result.Succeeded && !string.IsNullOrEmpty(model.Password))
                    {
                        await _userManager.RemovePasswordAsync(user);//parolasini silecegiz admin olarak
                        await _userManager.AddPasswordAsync(user, model.Password);//formdana gelen parolayi yeni parola gibi gonderecegiz
                    }
                    if (result.Succeeded)
                    {//eger result Succesd ise kulaniciyi  güncelle ve index e yönlendir
                        await _userManager.RemoveFromRolesAsync(user,await _userManager.GetRolesAsync(user));
                        if (model.SelectedRoles!=null)
                        {
                            await _userManager.AddToRolesAsync(user, model.SelectedRoles);

                        }
                        return RedirectToAction("Index");
                    }//eger kullanici success degilse hata göster ekranda
                    foreach (IdentityError err in result.Errors)
                    {
                        ModelState.AddModelError("",err.Description);//edit formu model seviyesindeki hatalarda burada kaynaklanan hatalari da gosterecek
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user!=null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

IdentityApp/Views/User/Create.cshtml
@model CreateUserViewModel

<div class="row align-content-center">
    <div class="col-md-8">
        <h1 class="h4 align-items-center">User Form</h1>
        <form asp-action="Create" method="post">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <div class="mb-3">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="FullName"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-info"><i class="fa-solid fa-plus"></i> Save</button>
        </form>
    </div>
</div>

IdentityApp/Views/User/Edit.cshtml
@model EditUserViewModel

<div class="row align-content-center">
    <div class="col">
        <h1 >Edit User Form</h1>
        <hr />
        <form asp-action="Edit" method="post">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="mb-3">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="FullName"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="row d-flex align-items-center">
                <div class="col-md-6">
                    <div class="card mb-3">
                        <div class="card-header">
                            <h4>Password Update</h4>
                        </div>
                        <div class="card-body">
                            <div class="mb-3">
                                <label asp-for="Password"></label>
                                <input asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="mb-3">
                                <label asp-for="ConfirmPassword"></label>
                                <input asp-for="ConfirmPassword" class="form-control" />
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" >
                    <div class="card mb-3">
                        <div class="card-header">
                            <h4>User Roles</h4>
                        </div>
                        <div class="card-body">
                            @foreach (var role in ViewBag.Roles)
                            {
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input"
                                           id="@role" value="@role" name="SelectedRoles"
                                    @if (Model.SelectedRoles != null)
                                    {
                                         @(Model.SelectedRoles.Any(i => i == role) ? "checked" : "") 
                                        
                                    } /><!--SelectedRoles EditUserViewModel e göre yazildi.-->
                                    <label class="form-check-label" for="@role">@role</label>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-info"><i class="fa-solid fa-plus"></i> Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

IdentityApp/Views/User/Index.cshtml
@model IEnumerable<AppUser>
<a class="btn btn-primary btn-sm p-2" asp-action="Create" asp-controller="User"><i class="fa-solid fa-user-plus"></i> Create User</a>
<hr />
<table class="table table-sm table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th style="width:300px">@Html.DisplayNameFor(itemModel=>itemModel.Id)</th>
            <th>@Html.DisplayNameFor(itemModel=>itemModel.UserName)</th>
            <th>@Html.DisplayNameFor(itemModel=>itemModel.FullName)</th>
            <th>@Html.DisplayNameFor(itemModel=>itemModel.Email)</th>
            <th style="width:150px">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id </td>
                <td>@item.UserName</td>
                <td>@item.FullName</td>
                <td>@item.Email</td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-route-id="@item.Id" asp-action="Edit" asp-controller="Roles"><i class="fa-solid fa-pen-to-square"></i> Edit</a>
                        <form method="post" asp-action="Delete" style="display:inline-block;" onsubmit="return confirm('Emin misiniz?')">
                            <!--onsubmit="return confirm('Emin misiniz?')" -->
                            <input type="hidden" name="id" value="@item.Id" />
                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i> Delete</button>
                    </form>
                
                </td>
            </tr>
        }
    </tbody>
</table>